[build]
publish = "docs/.vitepress/dist"
command = "pnpm docs:build"
base = "/"

# Allow previewing docs
[[redirects]]
from = "/docs/*"
to = "/:splat"
status = 200
force = true

# Redirect to Discord server
[[redirects]]
from = "https://chat.tsky.dev"
to = "https://discord.gg/KPD7XPUZn3"
status = 301
force = true
